### ISSUE TITLE
Allow PATCH /services/{service_id} payload to be different from POST /services/ payload

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-D28#11]
`POST /services/{service_id}` has a required parameter `type`, which isn't present when modifying a service. 

It should be allowed to specify different files for the 2 requests, as some backends don't allow unexpected parameters.

**Comment by lforesta** [comment]
@Ardweaden can you check if the PR is sufficient or if it requires further changes? Thanks

**Comment by Ardweaden** [comment]
@lforesta It's perfect, thank you.
