### ISSUE TITLE
from_argument in EODC_user_process.json

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-D28#3]
Hi, was looking into setting up a config file for the VITO backend and noticed that EODC_user_process.json users `from_argument` everywhere. Shouldn't that be `from_parameter` for process graph parameter references and `from_node` for node references?

**Comment by m-mohr** [comment]
Yes!

**Comment by lforesta** [comment]
Yes indeed, I will update the file after testing locally
