### ISSUE TITLE
what is `endpoints.jobs_post_1` ?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-D28#6]
what's the point of this?

https://github.com/Open-EO/openeo-D28/blob/b22612fa6cbe915ed51c1e97914854b664d86e3a/src/openeo_d28/openeo_v1.0_endpoints.toml#L169-L174

when there is already this:
https://github.com/Open-EO/openeo-D28/blob/b22612fa6cbe915ed51c1e97914854b664d86e3a/src/openeo_d28/openeo_v1.0_endpoints.toml#L115-L120

**Comment by soxofaan** [comment]
note that the `body` variable is unlike all other `body` variables, which have `body/` prefix

**Comment by lforesta** [comment]
This seems a mistake, I'll remove one of them
